---
deployment:
  tasks:
    - export BACKEND=/home2/everestautohub/backend
    - /bin/mkdir -p $BACKEND
    - /bin/cp -R everest-auto-hub/backend/* $BACKEND
    - cd /home2/everestautohub/backend && npm install --production
    - export DEPLOYPATH=/home2/everestautohub/public_html
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R everest-auto-hub/frontend/dist/* $DEPLOYPATH